sudo: required

services:
    - docker

before_install:
    - docker build -t ronek22/dev-ops -f mydockerfrontend/Dockerfile.dev mydockerfrontend/.

script:
    - docker run -e CI=true ronek22/dev-ops yarn test