apiVersion: apps/v1

kind: Deployment

metadata:
    name: mybackend-deployment
    labels:
        app: myapp-backend
        type: backend

spec:
    template:
        metadata:
            name: mybackend-pod
            labels:
                app: myapp-backend
                type: backend
        spec:
            containers:
                - name: my-backend-container
                  image: ronek22/running-calculator-backend
                  env:
                    - name: REDIS_HOST
                      value: 'myredisservice'
                    - name: REDIS_PORT
                      value: '6379'
                    - name: PGPASSWORD
                      valueFrom:
                          secretKeyRef:
                            name: myapp-secret
                            key: PGPASSWORD

                  envFrom:
                    - configMapRef:
                        name: postgres-config



    replicas: 3
    selector: 
        matchLabels:
            type: backend