version: '3'

services:
    my-backend:
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - /opt/app/node_modules
            - .:/opt/app

        environment: 
            - REDIS_HOST=my-redis
            - PGHOST=my-postgres
            - PGUSER=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=123qaz123qaz
            - PGPORT=5432

        depends_on: 
            - my-redis
            - my-postgres

    my-redis:
        image: redis

    my-postgres:
        image: postgres

