apiVersion: v1

kind: PersistentVolume

metadata:
  name: pv-volume1

spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /home/ronek22/tmp/k8s-volume1
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - docker-desktop